// Career navigation constants
// This file contains all hardcoded career path data used across the application

// Quick select domains for popular paths on landing page
export const quickSelectDomains = [
  { name: 'Software Engineering', category: 'engineering', field: 'Web Development' },
  { name: 'Data Science', category: 'emerging', field: 'Machine Learning' },
  { name: 'Digital Marketing', category: 'commerce', field: 'Social Media Marketing' },
  { name: 'UI/UX Design', category: 'design', field: 'User Experience Design' }
];

// Categories for career navigation
export const categories = [
  { id: 'engineering', name: 'Engineering & Technology', icon: '⚙️', description: 'Build the future with cutting-edge technology' },
  { id: 'medical', name: 'Medical & Healthcare', icon: '⚕️', description: 'Heal and help others in healthcare' },
  { id: 'commerce', name: 'Business & Management', icon: '💼', description: 'Lead organizations and drive innovation' },
  { id: 'design', name: 'Creative & Design', icon: '🎨', description: 'Express creativity through visual arts' },
  { id: 'law', name: 'Law & Public Service', icon: '⚖️', description: 'Serve justice and public interest' },
  { id: 'science', name: 'Sciences & Research', icon: '🔬', description: 'Explore the mysteries of our world' },
  { id: 'emerging', name: 'Emerging Fields', icon: '🚀', description: 'Pioneer the next big breakthroughs' },
  { id: 'education', name: 'Education & Teaching', icon: '📚', description: 'Shape minds and inspire future generations' },
  { id: 'media', name: 'Media & Communication', icon: '📺', description: 'Connect people through storytelling' },
  { id: 'agriculture', name: 'Agriculture & Environment', icon: '🌱', description: 'Sustain our planet for future generations' }
];

// Fields grouped by category
export const fieldsByCategory = {
  engineering: [
    'Software Engineering',
    'Mechanical Engineering',
    'Electrical Engineering',
    'Civil Engineering',
    'Chemical Engineering',
    'Aerospace Engineering',
    'Biomedical Engineering',
    'Environmental Engineering',
    'Industrial Engineering',
    'Materials Engineering',
    'Nuclear Engineering',
    'Petroleum Engineering'
  ],
  medical: [
    'General Medicine',
    'Surgery',
    'Pediatrics',
    'Psychiatry',
    'Dermatology',
    'Cardiology',
    'Neurology',
    'Orthopedics',
    'Ophthalmology',
    'Gynecology',
    'Radiology',
    'Anesthesiology'
  ],
  commerce: [
    'Business Administration',
    'Finance',
    'Marketing',
    'Human Resources',
    'Operations Management',
    'Entrepreneurship',
    'Economics',
    'Accounting',
    'Supply Chain Management',
    'International Business',
    'Business Analytics',
    'Strategic Management'
  ],
  design: [
    'Graphic Design',
    'Industrial Design',
    'Fashion Design',
    'Interior Design',
    'Animation',
    'Photography',
    'Film & Video Production',
    'Architecture',
    'Digital Media Arts',
    'Game Design',
    'UI/UX Design',
    'Creative Writing'
  ],
  law: [
    'Law',
    'Public Administration',
    'Political Science',
    'International Relations',
    'Criminal Justice',
    'Social Work',
    'Public Policy',
    'Diplomacy',
    'Non-Profit Management',
    'Urban Planning',
    'Public Health',
    'Emergency Management'
  ],
  science: [
    'Physics',
    'Chemistry',
    'Biology',
    'Mathematics',
    'Statistics',
    'Geology',
    'Astronomy',
    'Environmental Science',
    'Biotechnology',
    'Materials Science',
    'Nanotechnology',
    'Marine Science'
  ],
  emerging: [
    'Artificial Intelligence',
    'Data Science',
    'Cybersecurity',
    'Renewable Energy',
    'Bioinformatics',
    'Neuroscience',
    'Robotics',
    'Blockchain Technology',
    'Quantum Computing',
    'Computational Biology',
    'Digital Humanities',
    'Biotechnology'
  ],
  education: [
    'Early Childhood Education',
    'Primary Education',
    'Secondary Education',
    'Special Education',
    'Higher Education',
    'Educational Technology',
    'Curriculum Development',
    'Educational Psychology',
    'Adult Education',
    'Language Teaching',
    'Instructional Design',
    'Educational Leadership'
  ],
  media: [
    'Journalism',
    'Broadcasting',
    'Public Relations',
    'Digital Marketing',
    'Content Creation',
    'Social Media Management',
    'Film Production',
    'Radio Production',
    'Podcasting',
    'Media Studies',
    'Communications',
    'Advertising'
  ],
  agriculture: [
    'Agronomy',
    'Horticulture',
    'Animal Science',
    'Forestry',
    'Aquaculture',
    'Agricultural Engineering',
    'Soil Science',
    'Plant Science',
    'Food Science',
    'Environmental Conservation',
    'Sustainable Agriculture',
    'Agribusiness'
  ]
};

// Domains (specializations) grouped by field
export const domainsByField = {
  // Engineering domains
  'Software Engineering': [
    'Web Development',
    'Mobile Development',
    'Data Science',
    'Artificial Intelligence',
    'Cybersecurity',
    'DevOps',
    'Game Development',
    'Cloud Computing',
    'Blockchain',
    'IoT Development'
  ],
  'Mechanical Engineering': [
    'Thermodynamics',
    'Fluid Mechanics',
    'Robotics',
    'Automotive',
    'Aerospace',
    'Manufacturing',
    'HVAC',
    'CAD Design',
    'Automation',
    'Energy Systems'
  ],
  'Electrical Engineering': [
    'Power Systems',
    'Electronics',
    'Control Systems',
    'Signal Processing',
    'Telecommunications',
    'Embedded Systems',
    'Renewable Energy',
    'VLSI Design',
    'Instrumentation',
    'Smart Grids'
  ],
  'Civil Engineering': [
    'Structural Engineering',
    'Geotechnical Engineering',
    'Transportation',
    'Water Resources',
    'Construction Management',
    'Environmental Engineering',
    'Urban Planning',
    'Coastal Engineering',
    'Earthquake Engineering',
    'Surveying'
  ],
  'Chemical Engineering': [
    'Process Design',
    'Reaction Engineering',
    'Separation Processes',
    'Process Control',
    'Biochemical Engineering',
    'Polymer Engineering',
    'Environmental Engineering',
    'Pharmaceutical Engineering',
    'Food Processing',
    'Energy Conversion'
  ],
  'Aerospace Engineering': [
    'Aerodynamics',
    'Propulsion Systems',
    'Flight Mechanics',
    'Structural Analysis',
    'Avionics',
    'Space Systems',
    'Composite Materials',
    'Control Systems',
    'Thermal Systems',
    'Systems Engineering'
  ],
  'Biomedical Engineering': [
    'Medical Imaging',
    'Biomaterials',
    'Biomechanics',
    'Tissue Engineering',
    'Medical Devices',
    'Rehabilitation Engineering',
    'Clinical Engineering',
    'Genetic Engineering',
    'Neural Engineering',
    'Pharmaceutical Engineering'
  ],
  'Environmental Engineering': [
    'Water Treatment',
    'Air Pollution Control',
    'Waste Management',
    'Environmental Impact Assessment',
    'Sustainable Design',
    'Climate Change Mitigation',
    'Renewable Energy',
    'Environmental Monitoring',
    'Green Building',
    'Ecosystem Restoration'
  ],
  'Industrial Engineering': [
    'Operations Research',
    'Supply Chain Management',
    'Quality Control',
    'Facilities Planning',
    'Ergonomics',
    'Production Planning',
    'Lean Manufacturing',
    'Six Sigma',
    'Systems Integration',
    'Process Optimization'
  ],
  'Materials Engineering': [
    'Metallurgy',
    'Ceramics',
    'Polymers',
    'Composites',
    'Nanomaterials',
    'Biomaterials',
    'Electronic Materials',
    'Optical Materials',
    'Structural Materials',
    'Smart Materials'
  ],
  'Nuclear Engineering': [
    'Nuclear Reactor Design',
    'Radiation Protection',
    'Nuclear Fuel Cycle',
    'Nuclear Safety',
    'Medical Physics',
    'Nuclear Waste Management',
    'Plasma Physics',
    'Nuclear Instrumentation',
    'Radiation Biology',
    'Nuclear Security'
  ],
  'Petroleum Engineering': [
    'Reservoir Engineering',
    'Drilling Engineering',
    'Production Engineering',
    'Petrophysics',
    'Enhanced Oil Recovery',
    'Natural Gas Engineering',
    'Offshore Engineering',
    'Well Logging',
    'Reservoir Simulation',
    'Formation Evaluation'
  ],
  
  // Medical domains
  'General Medicine': [
    'Internal Medicine',
    'Family Medicine',
    'Emergency Medicine',
    'Geriatrics',
    'Palliative Care',
    'Hospitalist Medicine',
    'Preventive Medicine',
    'Travel Medicine',
    'Tropical Medicine',
    'Occupational Medicine'
  ],
  'Surgery': [
    'General Surgery',
    'Cardiac Surgery',
    'Neurosurgery',
    'Orthopedic Surgery',
    'Plastic Surgery',
    'Transplant Surgery',
    'Pediatric Surgery',
    'Trauma Surgery',
    'Oncological Surgery',
    'Minimally Invasive Surgery'
  ],
  'Pediatrics': [
    'General Pediatrics',
    'Pediatric Cardiology',
    'Pediatric Oncology',
    'Neonatology',
    'Pediatric Emergency',
    'Adolescent Medicine',
    'Pediatric Surgery',
    'Pediatric Neurology',
    'Child Development',
    'Pediatric Psychology'
  ],
  'Psychiatry': [
    'Adult Psychiatry',
    'Child Psychiatry',
    'Forensic Psychiatry',
    'Addiction Psychiatry',
    'Geriatric Psychiatry',
    'Psychosomatic Medicine',
    'Psychotherapy',
    'Community Psychiatry',
    'Clinical Neuropsychology',
    'Psychopharmacology'
  ],
  'Dermatology': [
    'Medical Dermatology',
    'Surgical Dermatology',
    'Cosmetic Dermatology',
    'Dermatopathology',
    'Pediatric Dermatology',
    'Mohs Surgery',
    'Contact Dermatitis',
    'Autoimmune Skin Disorders',
    'Skin Cancer Treatment',
    'Aesthetic Dermatology'
  ],
  'Cardiology': [
    'Interventional Cardiology',
    'Electrophysiology',
    'Heart Failure',
    'Preventive Cardiology',
    'Pediatric Cardiology',
    'Cardiac Imaging',
    'Nuclear Cardiology',
    'Cardiac Rehabilitation',
    'Congenital Heart Disease',
    'Valvular Heart Disease'
  ],
  'Neurology': [
    'General Neurology',
    'Stroke Neurology',
    'Epilepsy',
    'Movement Disorders',
    'Neuromuscular Medicine',
    'Headache Medicine',
    'Sleep Medicine',
    'Neuroimmunology',
    'Neuro-oncology',
    'Cognitive Neurology'
  ],
  'Orthopedics': [
    'Joint Replacement',
    'Sports Medicine',
    'Spine Surgery',
    'Trauma Surgery',
    'Pediatric Orthopedics',
    'Hand Surgery',
    'Foot & Ankle Surgery',
    'Shoulder Surgery',
    'Oncology Orthopedics',
    'Musculoskeletal Imaging'
  ],
  'Ophthalmology': [
    'Cornea & External Disease',
    'Retina & Vitreous',
    'Glaucoma',
    'Pediatric Ophthalmology',
    'Oculoplastics',
    'Neuro-ophthalmology',
    'Cataract Surgery',
    'Refractive Surgery',
    'Medical Retina',
    'Surgical Retina'
  ],
  'Gynecology': [
    'General Gynecology',
    'Gynecologic Oncology',
    'Reproductive Endocrinology',
    'Maternal-Fetal Medicine',
    'Urogynecology',
    'Pediatric Gynecology',
    'Gynecologic Laparoscopy',
    'Menopause Management',
    'Family Planning',
    'Gynecologic Pathology'
  ],
  'Radiology': [
    'Diagnostic Radiology',
    'Interventional Radiology',
    'Nuclear Medicine',
    'Radiation Oncology',
    'Pediatric Radiology',
    'Neuroradiology',
    'Musculoskeletal Radiology',
    'Breast Imaging',
    'Cardiac Imaging',
    'Emergency Radiology'
  ],
  'Anesthesiology': [
    'General Anesthesiology',
    'Cardiac Anesthesiology',
    'Pediatric Anesthesiology',
    'Neuroanesthesiology',
    'Pain Medicine',
    'Critical Care',
    'Regional Anesthesiology',
    'Ambulatory Anesthesiology',
    'Obstetric Anesthesiology',
    'Acute Pain Management'
  ],
  
  // Commerce domains
  'Business Administration': [
    'Strategic Management',
    'Operations Management',
    'Organizational Behavior',
    'Leadership Development',
    'Change Management',
    'Business Ethics',
    'Corporate Governance',
    'Performance Management',
    'Business Strategy',
    'Management Consulting'
  ],
  'Finance': [
    'Corporate Finance',
    'Investment Banking',
    'Risk Management',
    'Portfolio Management',
    'Financial Planning',
    'Real Estate Finance',
    'International Finance',
    'Financial Analysis',
    'Mergers & Acquisitions',
    'Behavioral Finance'
  ],
  'Marketing': [
    'Digital Marketing',
    'Brand Management',
    'Market Research',
    'Product Marketing',
    'Social Media Marketing',
    'Content Marketing',
    'Email Marketing',
    'SEO/SEM',
    'Marketing Analytics',
    'Customer Relationship Management'
  ],
  'Human Resources': [
    'Talent Acquisition',
    'Organizational Development',
    'Compensation & Benefits',
    'Employee Relations',
    'Training & Development',
    'HR Analytics',
    'Performance Management',
    'Succession Planning',
    'Workforce Planning',
    'HR Technology'
  ],
  'Operations Management': [
    'Supply Chain Management',
    'Process Improvement',
    'Quality Management',
    'Logistics Management',
    'Project Management',
    'Lean Management',
    'Six Sigma',
    'Inventory Management',
    'Production Planning',
    'Vendor Management'
  ],
  'Entrepreneurship': [
    'Startup Development',
    'Business Planning',
    'Funding & Investment',
    'Innovation Management',
    'Social Entrepreneurship',
    'Franchise Management',
    'Business Model Innovation',
    'Market Validation',
    'Scaling Strategies',
    'Exit Strategies'
  ],
  'Economics': [
    'Microeconomics',
    'Macroeconomics',
    'Econometrics',
    'Behavioral Economics',
    'Development Economics',
    'International Economics',
    'Public Economics',
    'Labor Economics',
    'Financial Economics',
    'Environmental Economics'
  ],
  'Accounting': [
    'Financial Accounting',
    'Managerial Accounting',
    'Auditing',
    'Tax Accounting',
    'Forensic Accounting',
    'Cost Accounting',
    'Internal Auditing',
    'Government Accounting',
    'International Accounting',
    'Accounting Information Systems'
  ],
  'Supply Chain Management': [
    'Logistics Management',
    'Procurement',
    'Warehouse Management',
    'Distribution Management',
    'Inventory Optimization',
    'Supplier Relationship Management',
    'Demand Planning',
    'Supply Chain Analytics',
    'Global Supply Chain',
    'Sustainable Supply Chain'
  ],
  'International Business': [
    'Global Strategy',
    'Cross-Cultural Management',
    'International Marketing',
    'Global Finance',
    'Trade Management',
    'Export/Import Operations',
    'International Law',
    'Global Sourcing',
    'Foreign Market Entry',
    'International Negotiations'
  ],
  'Business Analytics': [
    'Data Analytics',
    'Predictive Analytics',
    'Business Intelligence',
    'Data Visualization',
    'Statistical Analysis',
    'Machine Learning Applications',
    'Big Data Analysis',
    'Web Analytics',
    'Customer Analytics',
    'Financial Analytics'
  ],
  'Strategic Management': [
    'Corporate Strategy',
    'Competitive Analysis',
    'Strategic Planning',
    'Business Development',
    'Market Analysis',
    'Growth Strategies',
    'Strategic Alliances',
    'Innovation Strategy',
    'Digital Transformation',
    'Sustainability Strategy'
  ],
  
  // Design domains
  'Graphic Design': [
    'Branding Design',
    'Logo Design',
    'Packaging Design',
    'Print Design',
    'Editorial Design',
    'Digital Design',
    'Typography',
    'Motion Graphics',
    'Illustration',
    'Visual Identity Design'
  ],
  'Industrial Design': [
    'Product Design',
    'Ergonomics',
    'Materials & Manufacturing',
    'Design Research',
    'Rapid Prototyping',
    'Sustainability Design',
    'Consumer Electronics Design',
    'Automotive Design',
    'Furniture Design',
    'Medical Device Design'
  ],
  'Fashion Design': [
    'Apparel Design',
    'Textile Design',
    'Fashion Illustration',
    'Pattern Making',
    'Fashion Merchandising',
    'Costume Design',
    'Sustainable Fashion',
    'Fashion Marketing',
    'Collection Development',
    'Fashion Forecasting'
  ],
  'Interior Design': [
    'Residential Design',
    'Commercial Design',
    'Hospitality Design',
    'Space Planning',
    'Color Theory',
    'Lighting Design',
    'Sustainable Design',
    'Furniture Selection',
    'Kitchen & Bath Design',
    'Retail Design'
  ],
  'Animation': [
    '2D Animation',
    '3D Animation',
    'Character Animation',
    'Motion Graphics',
    'Visual Effects',
    'Storyboarding',
    'Rigging',
    'Compositing',
    'Animation Direction',
    'Stop Motion Animation'
  ],
  'Photography': [
    'Portrait Photography',
    'Landscape Photography',
    'Commercial Photography',
    'Fashion Photography',
    'Wedding Photography',
    'Photojournalism',
    'Wildlife Photography',
    'Architectural Photography',
    'Event Photography',
    'Fine Art Photography'
  ],
  'Film & Video Production': [
    'Cinematography',
    'Video Editing',
    'Directing',
    'Screenwriting',
    'Sound Design',
    'Producing',
    'Visual Effects',
    'Color Grading',
    'Documentary Filmmaking',
    'Film Production Management'
  ],
  'Architecture': [
    'Residential Architecture',
    'Commercial Architecture',
    'Sustainable Architecture',
    'Urban Design',
    'Landscape Architecture',
    'Interior Architecture',
    'Historic Preservation',
    'Architectural Visualization',
    'Building Information Modeling',
    'Architectural Project Management'
  ],
  'Digital Media Arts': [
    'Web Design',
    'User Interface Design',
    'User Experience Design',
    'Motion Graphics',
    'Interactive Media',
    'Digital Illustration',
    'Web Development',
    'Mobile App Design',
    'Game Design',
    'Virtual Reality Design'
  ],
  'Game Design': [
    'Game Mechanics',
    'Level Design',
    'Character Design',
    'Game Narrative',
    'Game Art',
    'Game Programming',
    'Virtual Reality Development',
    'Game Testing',
    'Game Production',
    'Game Monetization'
  ],
  'UI/UX Design': [
    'User Research',
    'Wireframing',
    'Prototyping',
    'User Interface Design',
    'User Experience Design',
    'Information Architecture',
    'Usability Testing',
    'Interaction Design',
    'Mobile Design',
    'Design Systems'
  ],
  'Creative Writing': [
    'Fiction Writing',
    'Non-Fiction Writing',
    'Screenwriting',
    'Poetry',
    'Technical Writing',
    'Copywriting',
    'Journalism',
    'Content Writing',
    'Ghostwriting',
    'Editing & Proofreading'
  ],
  
  // Law domains
  'Law': [
    'Criminal Law',
    'Civil Law',
    'Corporate Law',
    'Constitutional Law',
    'Family Law',
    'Employment Law',
    'Intellectual Property Law',
    'Environmental Law',
    'Tax Law',
    'Immigration Law'
  ],
  'Public Administration': [
    'Public Policy',
    'Government Management',
    'Public Finance',
    'Administrative Law',
    'Non-Profit Management',
    'Public Sector Leadership',
    'Program Evaluation',
    'Public Communications',
    'Crisis Management',
    'Regulatory Affairs'
  ],
  'Political Science': [
    'Comparative Politics',
    'International Relations',
    'Political Theory',
    'American Politics',
    'Public Policy',
    'Political Methodology',
    'Security Studies',
    'Democracy Studies',
    'Public Opinion',
    'Political Campaigns'
  ],
  'International Relations': [
    'Diplomacy',
    'Foreign Policy',
    'International Security',
    'Global Governance',
    'International Organizations',
    'Conflict Resolution',
    'Development Studies',
    'Human Rights',
    'International Law',
    'Global Political Economy'
  ],
  'Criminal Justice': [
    'Law Enforcement',
    'Criminology',
    'Corrections',
    'Forensics',
    'Criminal Psychology',
    'Juvenile Justice',
    'Victimology',
    'Crime Prevention',
    'Police Administration',
    'Security Management'
  ],
  'Social Work': [
    'Clinical Social Work',
    'Community Social Work',
    'Child & Family Services',
    'Mental Health Social Work',
    'Medical Social Work',
    'School Social Work',
    'Substance Abuse Social Work',
    'Geriatric Social Work',
    'Social Policy',
    'Social Work Administration'
  ],
  'Public Policy': [
    'Policy Analysis',
    'Policy Development',
    'Program Evaluation',
    'Policy Implementation',
    'Public Finance',
    'Regulatory Policy',
    'Social Policy',
    'Environmental Policy',
    'Health Policy',
    'Education Policy'
  ],
  'Diplomacy': [
    'Foreign Service',
    'International Negotiations',
    'Consular Affairs',
    'Cultural Diplomacy',
    'Public Diplomacy',
    'International Protocol',
    'Bilateral Relations',
    'Multilateral Diplomacy',
    'Crisis Diplomacy',
    'Diplomatic History'
  ],
  'Non-Profit Management': [
    'Grant Writing',
    'Fundraising',
    'Volunteer Management',
    'Program Management',
    'Non-Profit Finance',
    'Board Relations',
    'Community Outreach',
    'Advocacy',
    'Non-Profit Marketing',
    'Capacity Building'
  ],
  'Urban Planning': [
    'City Planning',
    'Regional Planning',
    'Transportation Planning',
    'Housing Policy',
    'Land Use Planning',
    'Environmental Planning',
    'Community Development',
    'Smart City Planning',
    'Urban Design',
    'Economic Development Planning'
  ],
  'Public Health': [
    'Epidemiology',
    'Health Policy',
    'Health Education',
    'Community Health',
    'Global Health',
    'Environmental Health',
    'Biostatistics',
    'Health Administration',
    'Disease Prevention',
    'Health Promotion'
  ],
  'Emergency Management': [
    'Disaster Preparedness',
    'Emergency Response',
    'Crisis Management',
    'Business Continuity',
    'Risk Assessment',
    'Emergency Planning',
    'Incident Management',
    'Recovery Planning',
    'Emergency Communications',
    'Public Safety'
  ],
  
  // Science domains
  'Physics': [
    'Theoretical Physics',
    'Experimental Physics',
    'Quantum Physics',
    'Astrophysics',
    'Condensed Matter Physics',
    'Particle Physics',
    'Optics',
    'Nuclear Physics',
    'Biophysics',
    'Applied Physics'
  ],
  'Chemistry': [
    'Organic Chemistry',
    'Inorganic Chemistry',
    'Physical Chemistry',
    'Analytical Chemistry',
    'Biochemistry',
    'Environmental Chemistry',
    'Materials Chemistry',
    'Medicinal Chemistry',
    'Computational Chemistry',
    'Industrial Chemistry'
  ],
  'Biology': [
    'Cell Biology',
    'Molecular Biology',
    'Genetics',
    'Ecology',
    'Evolutionary Biology',
    'Microbiology',
    'Zoology',
    'Botany',
    'Physiology',
    'Biotechnology'
  ],
  'Mathematics': [
    'Pure Mathematics',
    'Applied Mathematics',
    'Statistics',
    'Actuarial Science',
    'Computational Mathematics',
    'Mathematical Modeling',
    'Cryptography',
    'Mathematical Physics',
    'Topology',
    'Algebra'
  ],
  'Statistics': [
    'Applied Statistics',
    'Biostatistics',
    'Data Science',
    'Statistical Modeling',
    'Experimental Design',
    'Survey Methodology',
    'Bayesian Statistics',
    'Multivariate Analysis',
    'Time Series Analysis',
    'Statistical Computing'
  ],
  'Geology': [
    'Mineralogy',
    'Petrology',
    'Stratigraphy',
    'Structural Geology',
    'Geophysics',
    'Hydrogeology',
    'Economic Geology',
    'Environmental Geology',
    'Geomorphology',
    'Paleontology'
  ],
  'Astronomy': [
    'Observational Astronomy',
    'Theoretical Astrophysics',
    'Planetary Science',
    'Cosmology',
    'Stellar Astronomy',
    'Galactic Astronomy',
    'Exoplanet Research',
    'Radio Astronomy',
    'High-Energy Astrophysics',
    'Solar Physics'
  ],
  'Environmental Science': [
    'Ecology',
    'Conservation Biology',
    'Climate Science',
    'Environmental Chemistry',
    'Geoscience',
    'Marine Science',
    'Wetland Science',
    'Environmental Policy',
    'Sustainability Science',
    'Environmental Monitoring'
  ],
  'Biotechnology': [
    'Medical Biotechnology',
    'Agricultural Biotechnology',
    'Industrial Biotechnology',
    'Bioinformatics',
    'Genetic Engineering',
    'Protein Engineering',
    'Cell Culture',
    'Fermentation Technology',
    'Bioprocess Engineering',
    'Regulatory Affairs'
  ],
  'Materials Science': [
    'Nanotechnology',
    'Polymers',
    'Composites',
    'Metallurgy',
    'Ceramics',
    'Electronic Materials',
    'Biomaterials',
    'Smart Materials',
    'Computational Materials',
    'Materials Characterization'
  ],
  'Nanotechnology': [
    'Nanomaterials',
    'Nanoelectronics',
    'Nanomedicine',
    'Nanofabrication',
    'Molecular Nanotechnology',
    'Nanosensors',
    'Nanorobotics',
    'Nanochemistry',
    'Nanophysics',
    'Nanobiotechnology'
  ],
  'Marine Science': [
    'Oceanography',
    'Marine Biology',
    'Marine Geology',
    'Marine Chemistry',
    'Marine Physics',
    'Fisheries Science',
    'Marine Conservation',
    'Coastal Science',
    'Marine Policy',
    'Aquatic Ecology'
  ],
  
  // Emerging domains
  'Artificial Intelligence': [
    'Machine Learning',
    'Deep Learning',
    'Natural Language Processing',
    'Computer Vision',
    'Robotics',
    'Expert Systems',
    'Neural Networks',
    'Reinforcement Learning',
    'AI Ethics',
    'Autonomous Systems'
  ],
  'Data Science': [
    'Data Analysis',
    'Machine Learning',
    'Data Visualization',
    'Big Data',
    'Statistical Modeling',
    'Predictive Analytics',
    'Data Mining',
    'Business Intelligence',
    'Data Engineering',
    'Applied Statistics'
  ],
  'Cybersecurity': [
    'Network Security',
    'Information Security',
    'Ethical Hacking',
    'Digital Forensics',
    'Risk Management',
    'Incident Response',
    'Security Architecture',
    'Cryptography',
    'Identity Management',
    'Cloud Security'
  ],
  'Renewable Energy': [
    'Solar Energy',
    'Wind Energy',
    'Hydroelectric Power',
    'Geothermal Energy',
    'Biomass Energy',
    'Energy Storage',
    'Smart Grid Technology',
    'Energy Policy',
    'Sustainable Energy Systems',
    'Energy Efficiency'
  ],
  'Bioinformatics': [
    'Computational Biology',
    'Genomics',
    'Proteomics',
    'Molecular Modeling',
    'Sequence Analysis',
    'Systems Biology',
    'Drug Discovery',
    'Biostatistics',
    'Data Mining',
    'Clinical Bioinformatics'
  ],
  'Neuroscience': [
    'Cognitive Neuroscience',
    'Behavioral Neuroscience',
    'Clinical Neuroscience',
    'Computational Neuroscience',
    'Molecular Neuroscience',
    'Systems Neuroscience',
    'Neuroimaging',
    'Neurological Disorders',
    'Brain-Machine Interfaces',
    'Neural Engineering'
  ],
  'Robotics': [
    'Robot Design',
    'Robot Control',
    'Autonomous Systems',
    'Industrial Robotics',
    'Medical Robotics',
    'Human-Robot Interaction',
    'Robot Perception',
    'Robot Learning',
    'Swarm Robotics',
    'Robotic Engineering'
  ],
  'Blockchain Technology': [
    'Cryptocurrency Development',
    'Smart Contracts',
    'Decentralized Applications',
    'Consensus Mechanisms',
    'Blockchain Security',
    'Web3 Development',
    'Digital Asset Management',
    'Blockchain Architecture',
    'Token Economics',
    'Distributed Systems'
  ],
  'Quantum Computing': [
    'Quantum Algorithms',
    'Quantum Hardware',
    'Quantum Information Theory',
    'Quantum Cryptography',
    'Quantum Simulations',
    'Quantum Error Correction',
    'Quantum Computing Applications',
    'Quantum Software Development',
    'Quantum Machine Learning',
    'Quantum Networking'
  ],
  'Computational Biology': [
    'Biological Modeling',
    'Genomic Analysis',
    'Protein Structure Prediction',
    'Systems Biology',
    'Network Biology',
    'Phylogenetics',
    'Metabolic Modeling',
    'Evolutionary Biology',
    'Population Genetics',
    'Drug Design'
  ],
  'Digital Humanities': [
    'Text Analysis',
    'Data Visualization',
    'Digital Archives',
    'Cultural Analytics',
    'Human-Computer Interaction',
    'Digital Storytelling',
    'Computational Linguistics',
    'Spatial Humanities',
    'Network Analysis',
    'Digital Preservation'
  ],
  
  // Education domains
  'Early Childhood Education': [
    'Child Development',
    'Play-Based Learning',
    'Language Development',
    'Early Literacy',
    'Social-Emotional Learning',
    'Curriculum Design',
    'Classroom Management',
    'Parent Engagement',
    'Special Needs Education',
    'Assessment & Evaluation'
  ],
  'Primary Education': [
    'Elementary Teaching',
    'Curriculum Development',
    'Pedagogy',
    'Student Assessment',
    'Literacy Instruction',
    'Math Education',
    'Science Education',
    'Classroom Management',
    'Differentiated Instruction',
    'Educational Technology'
  ],
  'Secondary Education': [
    'High School Teaching',
    'Subject Area Expertise',
    'Curriculum Design',
    'Student Engagement',
    'Assessment Design',
    'Educational Psychology',
    'Classroom Management',
    'Project-Based Learning',
    'College Preparation',
    'Educational Leadership'
  ],
  'Special Education': [
    'Learning Disabilities',
    'Autism Spectrum Disorders',
    'Behavioral Interventions',
    'Assistive Technology',
    'Individualized Education Programs',
    'Inclusive Education',
    'Transition Planning',
    'Communication Disorders',
    'Adaptive Curriculum',
    'Student Advocacy'
  ],
  'Higher Education': [
    'Academic Administration',
    'Faculty Development',
    'Student Affairs',
    'Curriculum Design',
    'Academic Advising',
    'Research Administration',
    'Institutional Research',
    'Higher Education Policy',
    'Quality Assurance',
    'Educational Leadership'
  ],
  'Educational Technology': [
    'Learning Management Systems',
    'Instructional Design',
    'E-Learning Development',
    'Educational Software',
    'Technology Integration',
    'Digital Literacy',
    'Online Learning',
    'Educational Gaming',
    'Learning Analytics',
    'Multimedia Development'
  ],
  'Curriculum Development': [
    'Curriculum Design',
    'Instructional Materials',
    'Educational Standards',
    'Assessment Design',
    'Learning Objectives',
    'Educational Research',
    'Program Evaluation',
    'Content Development',
    'Educational Psychology',
    'Pedagogical Innovation'
  ],
  'Educational Psychology': [
    'Learning Theories',
    'Cognitive Development',
    'Motivation',
    'Educational Assessment',
    'Student Behavior',
    'Intelligence Testing',
    'Gifted Education',
    'At-Risk Students',
    'Mental Health in Education',
    'Applied Research'
  ],
  'Adult Education': [
    'Adult Learning Theory',
    'Continuing Education',
    'Professional Development',
    'Corporate Training',
    'Literacy Programs',
    'Distance Learning',
    'Program Planning',
    'Student Services',
    'Adult Career Development',
    'Educational Outreach'
  ],
  'Language Teaching': [
    'Second Language Acquisition',
    'Teaching English as Second Language',
    'Foreign Language Teaching',
    'Language Assessment',
    'Curriculum Design',
    'Language Technology',
    'Cultural Competency',
    'Bilingual Education',
    'Language Learning Methodologies',
    'Applied Linguistics'
  ],
  'Instructional Design': [
    'Learning Experience Design',
    'E-Learning Development',
    'Curriculum Design',
    'Assessment Design',
    'Educational Technology',
    'Multimedia Development',
    'User Experience in Education',
    'Performance Improvement',
    'Educational Analytics',
    'Training Program Development'
  ],
  'Educational Leadership': [
    'School Administration',
    'Educational Policy',
    'Organizational Leadership',
    'Strategic Planning',
    'Teacher Professional Development',
    'Student Success Initiatives',
    'Education Finance',
    'Community Engagement',
    'School Improvement',
    'Change Management'
  ],
  
  // Media domains
  'Journalism': [
    'Investigative Reporting',
    'Broadcast Journalism',
    'Digital Journalism',
    'Photojournalism',
    'Data Journalism',
    'Business Journalism',
    'Sports Journalism',
    'Entertainment Journalism',
    'Science Journalism',
    'Political Journalism'
  ],
  'Broadcasting': [
    'Television Production',
    'Radio Production',
    'Live Broadcasting',
    'News Production',
    'Sports Broadcasting',
    'Entertainment Production',
    'Technical Operations',
    'Broadcast Management',
    'Content Curation',
    'Audience Development'
  ],
  'Public Relations': [
    'Media Relations',
    'Crisis Communication',
    'Brand Communication',
    'Corporate Communications',
    'Social Media Management',
    'Event Management',
    'Public Affairs',
    'Community Relations',
    'Investor Relations',
    'Public Speaking'
  ],
  'Digital Marketing': [
    'Search Engine Optimization',
    'Search Engine Marketing',
    'Social Media Marketing',
    'Content Marketing',
    'Email Marketing',
    'Pay-Per-Click Advertising',
    'Marketing Analytics',
    'Conversion Optimization',
    'Influencer Marketing',
    'Digital Strategy'
  ],
  'Content Creation': [
    'Blogging',
    'Video Production',
    'Podcast Production',
    'Social Media Content',
    'Copywriting',
    'Content Strategy',
    'Multimedia Production',
    'Content Marketing',
    'Creative Direction',
    'Content Distribution'
  ],
  'Social Media Management': [
    'Community Management',
    'Content Strategy',
    'Social Media Analytics',
    'Influencer Relations',
    'Platform Management',
    'Crisis Management',
    'Brand Voice Development',
    'Campaign Management',
    'User Engagement',
    'Social Listening'
  ],
  'Film Production': [
    'Directing',
    'Producing',
    'Cinematography',
    'Editing',
    'Sound Design',
    'Visual Effects',
    'Production Management',
    'Screenwriting',
    'Distribution',
    'Film Finance'
  ],
  'Radio Production': [
    'Program Production',
    'Sound Engineering',
    'Voice Production',
    'Audio Editing',
    'Live Production',
    'Podcasting',
    'Content Development',
    'Station Management',
    'Music Programming',
    'Technical Operations'
  ],
  'Podcasting': [
    'Audio Production',
    'Storytelling',
    'Interviewing',
    'Audio Editing',
    'Distribution',
    'Podcast Marketing',
    'Monetization',
    'Content Strategy',
    'Equipment Management',
    'Audience Building'
  ],
  'Media Studies': [
    'Media Theory',
    'Cultural Studies',
    'Media Criticism',
    'Media History',
    'Digital Media',
    'Media Literacy',
    'Communication Research',
    'Media Policy',
    'Media Ethics',
    'Audience Studies'
  ],
  'Communications': [
    'Strategic Communication',
    'Organizational Communication',
    'Interpersonal Communication',
    'Mass Communication',
    'Crisis Communication',
    'Communication Research',
    'Public Speaking',
    'Writing & Editing',
    'Media Relations',
    'Communication Technology'
  ],
  'Advertising': [
    'Creative Strategy',
    'Copywriting',
    'Art Direction',
    'Media Planning',
    'Account Management',
    'Campaign Development',
    'Market Research',
    'Brand Positioning',
    'Digital Advertising',
    'Advertising Analytics'
  ],
  
  // Agriculture domains
  'Agronomy': [
    'Crop Production',
    'Soil Management',
    'Crop Breeding',
    'Plant Pathology',
    'Integrated Pest Management',
    'Precision Agriculture',
    'Sustainable Agriculture',
    'Irrigation Management',
    'Crop Nutrition',
    'Organic Farming'
  ],
  'Horticulture': [
    'Fruit Production',
    'Vegetable Production',
    'Floriculture',
    'Landscape Horticulture',
    'Greenhouse Management',
    'Plant Propagation',
    'Soil Science',
    'Integrated Pest Management',
    'Post-Harvest Technology',
    'Sustainable Horticulture'
  ],
  'Animal Science': [
    'Animal Breeding',
    'Animal Nutrition',
    'Animal Health',
    'Livestock Management',
    'Dairy Science',
    'Poultry Science',
    'Swine Management',
    'Beef Production',
    'Animal Behavior',
    'Animal Genetics'
  ],
  'Forestry': [
    'Forest Management',
    'Forest Ecology',
    'Silviculture',
    'Forest Conservation',
    'Wildlife Management',
    'Forest Products',
    'Urban Forestry',
    'Forest Policy',
    'Remote Sensing',
    'Sustainable Forestry'
  ],
  'Aquaculture': [
    'Fish Farming',
    'Shellfish Production',
    'Aquatic Health Management',
    'Nutrition & Feeding',
    'Water Quality Management',
    'Hatchery Management',
    'Aquaponics',
    'Sustainable Aquaculture',
    'Disease Management',
    'Environmental Impact'
  ],
  'Agricultural Engineering': [
    'Irrigation Engineering',
    'Farm Machinery',
    'Agricultural Automation',
    'Greenhouse Design',
    'Post-Harvest Engineering',
    'Energy Systems',
    'Water Management',
    'Drainage Engineering',
    'Agricultural Structures',
    'Precision Agriculture Technology'
  ],
  'Soil Science': [
    'Soil Chemistry',
    'Soil Physics',
    'Soil Biology',
    'Soil Fertility',
    'Soil Conservation',
    'Soil Classification',
    'Soil Survey',
    'Plant Nutrition',
    'Environmental Soil Science',
    'Sustainable Soil Management'
  ],
  'Plant Science': [
    'Plant Physiology',
    'Plant Breeding',
    'Plant Genetics',
    'Plant Pathology',
    'Plant Biotechnology',
    'Plant Ecology',
    'Plant Nutrition',
    'Crop Science',
    'Plant Systematics',
    'Sustainable Plant Production'
  ],
  'Food Science': [
    'Food Chemistry',
    'Food Processing',
    'Food Microbiology',
    'Food Safety',
    'Nutrition Science',
    'Food Product Development',
    'Quality Control',
    'Food Preservation',
    'Sensory Evaluation',
    'Food Regulations'
  ],
  'Environmental Conservation': [
    'Biodiversity Conservation',
    'Habitat Restoration',
    'Wildlife Conservation',
    'Ecosystem Management',
    'Environmental Monitoring',
    'Conservation Policy',
    'Sustainable Resource Management',
    'Climate Change Adaptation',
    'Protected Area Management',
    'Community-Based Conservation'
  ],
  'Sustainable Agriculture': [
    'Organic Farming',
    'Agroecology',
    'Permaculture',
    'Integrated Farming Systems',
    'Soil Conservation',
    'Water Conservation',
    'Renewable Energy in Agriculture',
    'Sustainable Livestock Management',
    'Organic Certification',
    'Local Food Systems'
  ],
  'Agribusiness': [
    'Agricultural Marketing',
    'Supply Chain Management',
    'Agricultural Finance',
    'Farm Management',
    'Agricultural Economics',
    'Commodity Trading',
    'Agricultural Policy',
    'Rural Development',
    'Agri-Tourism',
    'Agricultural Cooperatives'
  ]
};

