#!/bin/bash

echo "=== GitHub Personal Access Token Setup ==="
echo ""
echo "To push your MARGDARSHAN project to GitHub, you need a personal access token."
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to https://github.com/settings/tokens"
echo "2. Click 'Generate new token'"
echo "3. Give it a name (e.g., 'student_compass_deploy')"
echo "4. Select the 'repo' scope (check the box)"
echo "5. Click 'Generate token' at the bottom"
echo "6. COPY the token (you won't see it again)"
echo ""
echo "Once you have the token, run these commands:"
echo ""
echo "cd /Users/raheedpasha/Mini_Project/Generative"
echo "git remote set-url origin https://<YOUR_TOKEN_HERE>@github.com/Raheedpasha10/student_compass.git"
echo "git push -u origin main"
echo ""
echo "Replace <YOUR_TOKEN_HERE> with your actual token."
echo ""
echo "After running these commands, your repository will be visible at:"
echo "https://github.com/Raheedpasha10/student_compass"